# Generated by Django 5.1.1 on 2024-09-13 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Код купона")),
                (
                    "value",
                    models.IntegerField(
                        help_text="В процентах",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Размер скидки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
                "ordering": ["-value"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(upload_to="images", verbose_name="Изображение"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2024),
                        ],
                        verbose_name="ГОД",
                    ),
                ),
                ("country", models.CharField(max_length=70, verbose_name="Страна")),
                ("city", models.CharField(max_length=70, verbose_name="Город")),
                ("author", models.CharField(max_length=70, verbose_name="Художник")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата добавления"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["title", "-year"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Тут надо ввести название раздела",
                        max_length=70,
                        unique=True,
                        verbose_name="Название раздела",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "need_delivery",
                    models.BooleanField(verbose_name="Необходима доставка"),
                ),
                (
                    "name",
                    models.CharField(
                        default="Иванов Иван", max_length=70, verbose_name="Имя"
                    ),
                ),
                ("phone", models.CharField(max_length=70, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "notice",
                    models.TextField(blank=True, verbose_name="Примечание к заказу"),
                ),
                (
                    "date_order",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "date_send",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый заказ"),
                            ("APR", "Подтверждён"),
                            ("PAY", "Оплачен"),
                            ("CNL", "Отменён"),
                        ],
                        default="NEW",
                        max_length=3,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gallerydept.discount",
                        verbose_name="скидка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-date_order"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallerydept.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gallerydept.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка заказа",
                "verbose_name_plural": "Строки заказов",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gallerydept.section",
                verbose_name="Раздел",
            ),
        ),
    ]
