# Generated by Django 5.1.1 on 2024-09-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallerydept", "0002_product_materials"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                default=None, max_length=70, verbose_name="Размер (см.)"
            ),
            preserve_default=False,
        ),
    ]
