# Generated by Django 5.1.1 on 2024-09-27 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallerydept", "0003_product_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-date_order"],
                "permissions": (("can_set_status", "Возможность настройки статуса"),),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
