# Generated by Django 5.1.1 on 2024-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallerydept", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=40, verbose_name="Псевдоним"),
        ),
        migrations.AddField(
            model_name="section",
            name="slug",
            field=models.SlugField(default="", max_length=40, verbose_name="Псевдоним"),
        ),
    ]
